### ISSUE TITLE
DSC setup error

### ISSUE THREAD

**Issue by AtKnSploits** [h0nde/sel-discord#1]
#im debugging in pycharm 

Traceback (most recent call last):
  File "C:/Users/AtKn/PycharmProjects/Pythoncuk/lol.py", line 7, in <module>
    dsc.setup()
  File "C:\Users\AtKn\AppData\Local\Programs\Python\Python38-32\lib\seldiscord\sessions.py", line 57, in setup
    self.fingerprint = data["fingerprint"]
KeyError: 'fingerprint'

Process finished with exit code 1

#my code is :

import seldiscord
from time import sleep

user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"

with seldiscord.Session(user_agent) as dsc:
  dsc.setup()
  sleep(1)

  print(dsc.register(
    username="test309438832",
    password="i+=)('!+!'()=+!s",

  ))
  dsc.gateway()

**Comment by h0nde** [comment]
is your current IP address banned from discord?

**Comment by AtKnSploits** [comment]
> is your current IP address banned from discord?

i dont know but can be banned
i cant use webhooks on roblox studio scripts

**Comment by AtKnSploits** [comment]
i tryed an example only got this error
Worker error: 'token' <class 'KeyError'>
Worker error: 'token' <class 'KeyError'>
Worker error: 'token' <class 'KeyError'>
Worker error: 'token' <class 'KeyError'>
Worker error: 'token' <class 'KeyError'>

**Comment by TARNATlON** [comment]
Did you fix it AtKnSploits?
