### ISSUE TITLE
javascript error: Failed to fetch

### ISSUE THREAD

**Issue by HuskyCodez** [h0nde/sel-discord#3]
`Worker error: javascript error: Failed to fetch
  (Session info: headless chrome=86.0.4240.193) <class 'selrequests.exceptions.RequestException'>`

**Comment by AtKnSploits** [comment]
same

**Comment by SploeCyber** [comment]
same

**Comment by h0nde** [comment]
This error usually occurs when the proxy you're trying to use is dead
