### ISSUE TITLE
self.token = data["token"] - KeyError: 'token'

### ISSUE THREAD

**Issue by T0x1c3r** [h0nde/sel-discord#7]
So this has been killing me for the past couple of days a lot.

I've been trying to generate at least 1 token but I've hit this error every single time.

`self.token = data["token"]
KeyError: 'token'`

The most similar issue to this that I found is [AtKnSploits](https://github.com/h0nde/sel-discord/issues/1) issue, the only thing thats different is his is "fingerprint" & he closed his without saying what fixed his problem.

I am 99% sure it is not the proxy. Once I hit the error, I open my browser with that same proxy connected and I am able to make a discord account - so im pretty sure it isn't the proxys ip being banned.

Im completely stumped - I even tried the usage example on the README page.

Any ideas?

**Comment by AtKnSploits** [comment]
same error

**Comment by SploeCyber** [comment]
## It worked great for me.
![Screenshot](https://user-images.githubusercontent.com/37950018/100162132-7594b300-2ee5-11eb-8c8e-b228cdd75f43.png)

**Comment by AtKnSploits** [comment]
> ## It worked great for me.
> ![Screenshot](https://camo.githubusercontent.com/c4f4db35a88894e0f3726054481dccfd86dc86b29524e4219ad271e6b9e8ac97/68747470733a2f2f73686172652e73706c6f652e66756e2f663831494e7944772e706e67)

You using linux?

**Comment by SploeCyber** [comment]
> > ## It worked great for me.
> > ![Screenshot](https://camo.githubusercontent.com/c4f4db35a88894e0f3726054481dccfd86dc86b29524e4219ad271e6b9e8ac97/68747470733a2f2f73686172652e73706c6f652e66756e2f663831494e7944772e706e67)
> 
> You using linux?

yes

**Comment by AtKnSploits** [comment]
> > > ## It worked great for me.
> > > ![Screenshot](https://camo.githubusercontent.com/c4f4db35a88894e0f3726054481dccfd86dc86b29524e4219ad271e6b9e8ac97/68747470733a2f2f73686172652e73706c6f652e66756e2f663831494e7944772e706e67)
> > 
> > You using linux?
> 
> yes

How did you install chrome and chromedriver to linux

**Comment by SploeCyber** [comment]
> How did you install chrome and chromedriver to linux

You have to install chrome first
1. `wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`
2. `sudo apt install ./google-chrome-stable_current_amd64.deb`
Also, install chromedriver
3. `sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4`
4. `wget https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip`
5. `unzip chromedriver_linux64.zip`
6. `sudo mv chromedriver /usr/bin/chromedriver
sudo chown root:root /usr/bin/chromedriver
sudo chmod +x /usr/bin/chromedriver`

**Comment by AtKnSploits** [comment]
> > How did you install chrome and chromedriver to linux
> 
> You have to install chrome first
> 
> 1. `wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`
> 2. `sudo apt install ./google-chrome-stable_current_amd64.deb`
>    Also, install chromedriver
> 3. `sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4`
> 4. `wget https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip`
> 5. `unzip chromedriver_linux64.zip`
> 6. `sudo mv chromedriver /usr/bin/chromedriver sudo chown root:root /usr/bin/chromedriver sudo chmod +x /usr/bin/chromedriver`

i tryed on kali linux but token error again

**Comment by T0x1c3r** [comment]
> > > ## It worked great for me.
> > > ![Screenshot](https://camo.githubusercontent.com/c4f4db35a88894e0f3726054481dccfd86dc86b29524e4219ad271e6b9e8ac97/68747470733a2f2f73686172652e73706c6f652e66756e2f663831494e7944772e706e67)
> > 
> > 
> > You using linux?
> 
> yes

Where did you get your proxies from? I don't think my proxies are the issue here as I can connect to it via my browser settings and create a discord account on my browser but it's the only thing I can think of that would cause this issue.

**Comment by SploeCyber** [comment]
You can ignore errors because they are not really problem. About free proxy that I recommend, it is  openproxy.space and you have to use protocol as http

**Comment by zgredziczek** [comment]
> ## It worked great for me.
> ![Screenshot](https://camo.githubusercontent.com/c4f4db35a88894e0f3726054481dccfd86dc86b29524e4219ad271e6b9e8ac97/68747470733a2f2f73686172652e73706c6f652e66756e2f663831494e7944772e706e67)

Can you tell what you did that works? I tested on windows 10 and debian 10 and still the same bugs.
My code is from the example.
Proxy http all tested
![image](https://user-images.githubusercontent.com/50105477/100547145-6c00a780-3265-11eb-8200-8488c990218a.png)

**Comment by Ixkt** [comment]
> So this has been killing me for the past couple of days a lot.
> 
> I've been trying to generate at least 1 token but I've hit this error every single time.
> 
> `self.token = data["token"] KeyError: 'token'`
> 
> The most similar issue to this that I found is [AtKnSploits](https://github.com/h0nde/sel-discord/issues/1) issue, the only thing thats different is his is "fingerprint" & he closed his without saying what fixed his problem.
> 
> I am 99% sure it is not the proxy. Once I hit the error, I open my browser with that same proxy connected and I am able to make a discord account - so im pretty sure it isn't the proxys ip being banned.
> 
> Im completely stumped - I even tried the usage example on the README page.
> 
> Any ideas?

Hi have you fixed it ?

**Comment by Ixkt** [comment]
> > ## It worked great for me.
> > ![Screenshot](https://camo.githubusercontent.com/c4f4db35a88894e0f3726054481dccfd86dc86b29524e4219ad271e6b9e8ac97/68747470733a2f2f73686172652e73706c6f652e66756e2f663831494e7944772e706e67)
> 
> Can you tell what you did that works? I tested on windows 10 and debian 10 and still the same bugs.
> My code is from the example.
> Proxy http all tested
> ![image](https://user-images.githubusercontent.com/50105477/100547145-6c00a780-3265-11eb-8200-8488c990218a.png)

Same problem T_T

**Comment by zgredziczek** [comment]
I used the code from the example and it worked

**Comment by zgredziczek** [comment]
I guess using a proxy doesn't work

**Comment by T0x1c3r** [comment]
> > So this has been killing me for the past couple of days a lot.
> > I've been trying to generate at least 1 token but I've hit this error every single time.
> > `self.token = data["token"] KeyError: 'token'`
> > The most similar issue to this that I found is [AtKnSploits](https://github.com/h0nde/sel-discord/issues/1) issue, the only thing thats different is his is "fingerprint" & he closed his without saying what fixed his problem.
> > I am 99% sure it is not the proxy. Once I hit the error, I open my browser with that same proxy connected and I am able to make a discord account - so im pretty sure it isn't the proxys ip being banned.
> > Im completely stumped - I even tried the usage example on the README page.
> > Any ideas?
> 
> Hi have you fixed it ?

I have not. I tried 10 private proxies, 30k scanned proxies via KPortScanner which should be private, public proxies & the proxy site recommended above.

**Comment by T0x1c3r** [comment]
I think I have a start to this problem. I've played around with it and did some simple debugging and discord returns `{'captcha_key': ['captcha-required']}`.

Since some people are having this problem and others are not I think discord also checks the IP address to see if its a proxy or not to display a captcha.

**Comment by HuskyCodez** [comment]
> I think I have a start to this problem. I've played around with it and did some simple debugging and discord returns `{'captcha_key': ['captcha-required']}`.
> 
> Since some people are having this problem and others are not I think discord also checks the IP address to see if its a proxy or not to display a captcha.

or perhaps the free proxy was used somewhere else too many times
